;
ALTER USER SA RENAME TO MEDICAL_ADMIN;
ALTER USER MEDICAL_ADMIN SET PASSWORD 'gj264jgb63jn';
CREATE TABLE RECORDS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PERSON VARCHAR(255),
    TAKEN DATE,
    TESTS VARCHAR(1024)
);

CREATE TABLE TESTS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(1024)
);

CREATE TABLE RECORD_TEST(
    RECORD_ID INT,
    TEST_ID INT
);

ALTER TABLE RECORD_TEST ADD FOREIGN KEY(RECORD_ID) REFERENCES RECORDS(ID);
ALTER TABLE RECORD_TEST ADD FOREIGN KEY(TEST_ID) REFERENCES TESTS(ID);